version: '3'
services:
  notification-service-mysql:
    image: mysql:8.0
    container_name: notification-service-mysql
    environment:
      - MYSQL_DATABASE=notification-service
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306

  feathersjs-sequelize-transaction-across-multiple-services:
    image: node:14-alpine
    container_name: feathersjs-sequelize-transaction-across-multiple-services
    working_dir: /app
    restart: always
    command: sh -c "nc notification-service-mysql 3306 -e pwd && npm install && npm run start"
    ports:
      - "3030:3030"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=notification-service-mysql
      - DB_PORT=3306
      - DB_SCHEMA=notification-service
    volumes:
      - ../:/app:z
    depends_on:
      - notification-service-mysql
